name: hop_unittest
version: 0.1.0+1
author: Kevin Moore <kevmoo@google.com>
description: Hop task for running unit tests based on
homepage: https://github.com/kevmoo/hop_unittest
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.11.0 <0.12.0'
  hop: '>=0.30.0 <0.32.0'
  unittest: '>=0.11.0 <0.12.0'
dev_dependencies:
  hop_docgen: '>=0.1.3 <0.2.0'
